apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: anitapati/backstage
spec:
  type: website
  lifecycle: experimental
  owner: guests
